version: '3'
services:
  ethereum:
    image: trufflesuite/ganache-cli:v6.9.1
    ports:
      - '8545:8545'
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --deterministic
      - --mnemonic
      - '${MNEMONIC-minimum symptom minute gloom tragic situate silver mechanic salad amused elite beef}'
      - --hostname
      - '0.0.0.0'
      #- --fork 
      #- https://mainnet.infura.io/v3/${INFURA_TOKEN}@11001803
      # - --blockTime
      - --networkId
      - '123'
      - --defaultBalanceEther
      - '100000000'
      # - '2'
      #- --debug
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
      - ethereum
    environment:
      postgres_host: postgres:5432
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'local:http://ethereum:8545'
      RUST_LOG: info
  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - '5001:5001'
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
