version: '3'
services:
  ethereum:
    image: trufflesuite/ganache-cli:v6.9.1
    ports:
      - '8545:8545'
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --deterministic
      - --mnemonic
      - '${MNEMONIC-minimum symptom minute gloom tragic situate silver mechanic salad amused elite beef}'
      - --hostname
      - '0.0.0.0'
      #- --fork 
      - https://mainnet.infura.io/v3/${INFURA_TOKEN}@11001803
      # - --blockTime
      - --networkId
      - '123'
      - --defaultBalanceEther
      - '1000000'
      # - '2'
      #- --debug
